import { IconChevronDown, IconChevronUp } from '@tabler/icons-react';
import React, { useState } from 'react';

interface FAQItem {
  question: string;
  answer: string;
}

const faqData: FAQItem[] = [
  {
    question: 'What is AI image metadata extraction?',
    answer:
      'AI image metadata extraction is the process of automatically analyzing AI-generated images to retrieve embedded information such as generation prompts, model parameters, sampling steps, CFG scale, seed values, and other technical details used during the image creation process.',
  },
  {
    question: 'How does PicPic work with Stable Diffusion and ComfyUI?',
    answer:
      'PicPic can read and extract metadata from PNG images generated by Stable Diffusion and ComfyUI. It automatically detects the embedded parameters, prompts, and settings used during generation, making it easy to understand how any AI image was created.',
  },
  {
    question: 'Can PicPic extract prompts from AI images?',
    answer:
      'Yes! PicPic can extract original generation prompts from AI images that have embedded metadata. Additionally, our AI-powered reverse engineering feature can analyze images without metadata and reconstruct likely prompts that could have been used to create similar images.',
  },
  {
    question: 'What file formats does PicPic support?',
    answer:
      "Currently, PicPic supports PNG format images generated by Stable Diffusion and ComfyUI. We're working on adding support for DALL-E and Midjourney formats in future updates.",
  },
  {
    question: 'Is PicPic free to use?',
    answer:
      'Yes, PicPic is completely free to use! We offer all core features including metadata extraction, auto-tagging, prompt translation, and export functionality at no cost. Join our wishlist to be notified when we launch.',
  },
  {
    question: 'How accurate is the AI auto-tagging system?',
    answer:
      'Our AI auto-tagging system uses advanced computer vision algorithms to achieve high accuracy in identifying visual elements, styles, and characteristics in AI-generated images. The system continuously learns and improves to provide more precise tags for better image organization.',
  },
  {
    question: 'Can I export my image analysis data?',
    answer:
      'Absolutely! PicPic offers one-click export functionality in multiple formats including HTML for interactive web viewing and CSV for spreadsheet analysis. This makes it easy to share, analyze, and backup your image collection data.',
  },
  {
    question: 'Is there a browser extension available?',
    answer:
      'Yes! We offer a convenient browser extension that allows you to add images for analysis with just one click from any website. This makes the extraction process seamless and efficient when browsing AI art galleries or social media.',
  },
];

const FAQ: React.FC = () => {
  const [openItems, setOpenItems] = useState<number[]>([]);

  const toggleItem = (index: number) => {
    setOpenItems((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index],
    );
  };

  return (
    <div className="mx-auto max-w-4xl px-6 py-16">
      <div className="mb-12 text-center">
        <h2 className="mb-4 text-4xl font-bold text-white">
          Frequently Asked Questions
        </h2>
        <p className="text-xl text-gray-300">
          Everything you need to know about PicPic AI Image Analysis Tool
        </p>
      </div>

      <div className="space-y-4">
        {faqData.map((item, index) => (
          <div
            key={index}
            className="overflow-hidden rounded-lg border border-gray-700 bg-dark-800 transition-all duration-200 hover:border-primary-400"
          >
            <button
              onClick={() => toggleItem(index)}
              className="flex w-full items-center justify-between px-6 py-4 text-left focus:outline-none focus:ring-2 focus:ring-inset focus:ring-primary-400"
            >
              <h3 className="pr-4 text-lg font-semibold text-white">
                {item.question}
              </h3>
              {openItems.includes(index) ? (
                <IconChevronUp className="size-5 shrink-0 text-primary-400" />
              ) : (
                <IconChevronDown className="size-5 shrink-0 text-gray-400" />
              )}
            </button>

            {openItems.includes(index) && (
              <div className="px-6 pb-4">
                <div className="border-t border-gray-700 pt-4">
                  <p className="leading-relaxed text-gray-300">{item.answer}</p>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="mt-12 text-center">
        <p className="text-gray-400">
          Have more questions?{' '}
          <a
            href="mailto:support@picpic.ai"
            className="text-primary-400 transition-colors hover:text-primary-300"
          >
            Contact our support team
          </a>
        </p>
      </div>
    </div>
  );
};

export default FAQ;
export { faqData };
